[tool.poetry]
name = "pip"
version = "0.1.0"
description = "only available in pypi pip"
authors = ["Jan Weil <albcycle@gmx.net>"]

[tool.poetry.dependencies]
# last changed on 30.06.2021
# Tkinter table / sheet widget
tksheet = "^5.0.27"
# Calendar and Dateentry widgets for Tkinter
tkcalendar = "^1.6.1"
# a Coding Language for GUIs
Tcl = "^0.2"
# Python Publish-Subscribe Package
PyPubSub = "^4.0.3"
 
[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

